apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cicd-app-blue
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-cicd-app
      slot: blue
  template:
    metadata:
      labels:
        app: my-cicd-app
        slot: blue
    spec:
      containers:
      - name: my-cicd-app
        image: us-central1-docker.pkg.dev/able-folio-490803-g2/my-app/app:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: my-cicd-app-service
  namespace: production
spec:
  selector:
    app: my-cicd-app
    slot: blue
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer

